version: '3.8'

services:
  api:
    build: .
    ports:
      - "3005:3005"
    environment:
      DB_HOST: db  # Mantenha o nome do seu container MySQL aqui
      DB_USER: usuario
      DB_PASSWORD: senha
      DB_NAME: api
